--- #YAML:1.0
name:               Geo-KML
version:            0.93
abstract:           Create GoogleEarth and -Map KML/KMZ
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:         1.3
    Data::Peek:           0.32
    Log::Report:          0.28
    Test::More:           0.54
    XML::Compile:         1.18
    XML::Compile::Cache:  0.97
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
