=head1 NAME

Geo::KML::Util - Utility routines for Geo::KML components

=head1 INHERITANCE

 Geo::KML::Util
   is a Exporter

=head1 SYNOPSIS

 use Geo::KML::Util qw/:kml220/;

=head1 DESCRIPTION

The functions provided by this package are used by various Geo::KML
components, which on their own may be unrelated.

=head1 FUNCTIONS

=head2 Constants

The following URIs are exported as constants, to avoid typinng
in the same long URIs each time again.  These constants are,

=head3 Tag group :kml21

NS_KML_21 (KML namespace)

=head3 Tag group :kml22beta

NS_KML_22BETA,  NS_ATOM_2005, NS_XAL_20.

=head3 Tag group :kml220

NS_KML_22, NS_KML_220, NS_ATOM_2005, NS_XAL_20.

=head3 Tag group :mime

MIME_KML, MIME_KMZ

=head1 SEE ALSO

This module is part of Geo-KML distribution version 0.92,
built on December 24, 2010. Website: F<http://perl.overmeer.net/geo-kml>
All modules in this suite:
L</Geo::Point>,
L</Geo::Proj4>,
L</Geo::WKT>,
L</Math::Polygon>,
L</Geo::GML>,
L</Geo::ISO19139>,
L</Geo::EOP>,
L</Geo::Format::Envisat>, and
L</Geo::Format::Landsat>.

Please post questions or ideas to the mailinglist at
F<http://geo-perl@list.hut.fi>

=head1 LICENSE

Copyrights 2008-2010 by Mark Overmeer. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

